Added more events to complete the event pipelines
Alokit-Innovations/team-monitor-website pull request #95
Opened 2023-06-13 15:43 UTC by MuskanPaliwal

- There are a few events where we are supposed to check if user is logged-in and use his `user_id` instead `anonymous_id` but I ignored it as of now, since it seemed a tedious task.
- Will create an issue for that.

2023-06-13 15:50 UTC, tapishr commented
So we will get anonymous id even when the user is logged in?

2023-06-13 15:50 UTC, tapishr approved these changes

2023-06-13 15:53 UTC, MuskanPaliwal commented
> So we will get anonymous id even when the user is logged in?

Yeah

2023-06-16 10:00 UTC, tapishr submitted a review, later dismissed

2023-06-21 05:35 UTC, MuskanPaliwal commented
-This PR address all the issues regarding event pipeline
- Changed data-type of `userId` from `number` to `string` 
- Reflected the similar change in DB as well

2023-06-21 07:25 UTC, tapishr approved these changes
Please change the sql tables as well before merging so queries dont fail. If possible, test with db before merging

2023-06-21 07:27 UTC, MuskanPaliwal commented
> Please change the sql tables as well before merging so queries dont fail. If possible, test with db before merging

I did that last night itself and ab sab kuch phatt raha hain so meri PR should be merged asap 🥲

2023-06-21 12:24 UTC, avikalpg requested changes

2023-06-21 12:24 UTC, avikalpg commented on views/RepoList.tsx
> +		FROM ` + ((!convert(userId)) ? "commits AS c" : `(SELECT
unnecessary.

2023-06-21 12:56 UTC, avikalpg commented on components/LoginLogout.tsx
> +					<li id='logout-link' className='p-2 text-center cursor-pointer' onClick={() => { if (rudderEventMethods) {logout(getAuthUserId(session), getAuthUserName(session), getAndSetAnonymousIdFromLocalSt
This restricts logging out if `rudderEventMethods` are not found.
Maybe don't stop a person for being able to log out.

2023-06-21 12:58 UTC, avikalpg commented on components/LoginLogout.tsx
> +		  }}} className="rounded bg-inherit sm:bg-primary-main text-secondary-main py-2 px-4 font-semibold">
same as above.

2023-06-21 13:21 UTC, avikalpg commented on pages/docs/index.tsx
> +	const { rudderEventMethods } = React.useContext(RudderContext);
Please check: I think you have already done this in _app.tsx

2023-06-21 13:24 UTC, avikalpg commented on pages/index.tsx
> +import { Session } from 'next-auth'
```suggestion
import type { Session } from 'next-auth'
```

2023-06-21 13:25 UTC, avikalpg commented on pages/index.tsx
> +import { useSession } from 'next-auth/react'
remove unnecessary import.

2023-06-22 04:33 UTC, avikalpg commented on utils/auth.ts
> +export const getAuthUserId = (session: Session | null) => session?.user.id ? session.user.id : "0";
```suggestion
export const getAuthUserId = (session: Session | null) => session?.user.id ? session.user.id : "";
```

2023-06-22 04:39 UTC, avikalpg commented on pages/docs/index.tsx
> +			rudderEventMethods?.track(getAuthUserId(session), "Install github app ", { type: "link", eventStatusFlag: 1, source: "docs", name: getAuthUserName(session) }, anonymousId)
```suggestion
			rudderEventMethods?.track(getAuthUserId(session), "Install github app", { type: "link", eventStatusFlag: 1, source: "docs", name: getAuthUserName(session) }, anonymousId)
```

2023-06-22 04:39 UTC, avikalpg commented on pages/docs/index.tsx
> +			rudderEventMethods?.track(getAuthUserId(session), "Authorise bitbucket consumer button", { type: "button", eventStatusFlag: 1, source: "docs", name: getAuthUserName(session) }, anonymousId)
```suggestion
			rudderEventMethods?.track(getAuthUserId(session), "Authorise bitbucket consumer", { type: "button", eventStatusFlag: 1, source: "docs", name: getAuthUserName(session) }, anonymousId)
```

2023-06-22 04:45 UTC, avikalpg commented on pages/docs/index.tsx
> +import { Session } from 'next-auth'
```suggestion
import type { Session } from 'next-auth'
```

2023-06-22 04:52 UTC, avikalpg commented on pages/pricing.tsx
> +import { Session } from 'next-auth'
```suggestion
import type { Session } from 'next-auth'
```

2023-06-22 04:58 UTC, avikalpg commented on pages/pricing.tsx
> +		rudderEventMethods?.track(getAuthUserId(session), "pricing-page", { type: "page", eventStatusFlag: 1, name: getAuthUserName(session) }, anonymousId) //Anonymous Id is set in local storage as soon a
```suggestion
		rudderEventMethods?.track(getAuthUserId(session), "pricing-page", { type: "page", eventStatusFlag: 1, name: getAuthUserName(session) }, anonymousId) //Anonymous Id is set in local storage as soon as the user lands on the website.
```

2023-06-22 05:01 UTC, avikalpg commented on pages/pricing.tsx
> +		rudderEventMethods?.track(getAuthUserId(session), "pricing-page", { type: "page", eventStatusFlag: 1, name: getAuthUserName(session) }, anonymousId) //Anonymous Id is set in local storage as soon a
```suggestion
		rudderEventMethods?.track(getAuthUserId(session), "pricing-page", { type: "page", eventStatusFlag: 1, name: getAuthUserName(session) }, anonymousId)
```

2023-06-22 05:15 UTC, avikalpg commented on pages/u.tsx
> +		rudderEventMethods?.track(getAuthUserId(session), "Repo Profile Page", { type: "page", name: getAuthUserName(session) }, anonymousId);
```suggestion
		rudderEventMethods?.track(getAuthUserId(session), "User Profile Page", { type: "page", name: getAuthUserName(session) }, anonymousId);
```

2023-06-22 05:27 UTC, avikalpg commented on views/JoinSlack.tsx
> +			rudderEventMethods?.track(getAuthUserId(session), "join slack", { type: "button", eventStatusFlag: 1, name: getAuthUserName(session) }, anonymousId)
add `source: "landing page banner"`

2023-06-22 05:34 UTC, avikalpg approved these changes

2023-06-22 05:35 UTC, merged